<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/css/default.css" rel="stylesheet">

</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">
    <div class="container">
        <?php echo $this->action('header','index'); ?>

        <?php echo $this->layout()->content; ?>

        <?php echo $this->action('footer','index'); ?>
    </div> <!-- /Container -->

    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/default.js"></script>
</body>
</html>